FROM ubuntu:22.04

# Dependencies
RUN apt-get update && apt-get install -y \
    cmake \
    g++ \
    git \
    libmysqlclient-dev \
    libuv1-dev \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app
COPY . .

# Build
RUN mkdir build && cd build && \
    cmake -DCMAKE_BUILD_TYPE=Release .. && \
    cmake --build . --target thegrid_auth

# Run
EXPOSE 3000
CMD ["./build/thegrid_auth"]
